### PR TITLE
add tests

### LINKED ISSUE #12: We need tests
Mistakes in this packages are too severe and complex to test manually. We need a proper testing suite. Ideally the same tech as in tresor-import

### PR DESCRIPTION
**Pull request by naduweisstschon**
Added the basic testing infrastructure using ```jest```, and some tests for functions that I could wrap my head around (Resolves #12).

There is (at least in my eyes?) an issue with ```calcInventoryPurchasesFIFO``` that I have fixed. It makes the assumption that activities are passed in the reverse order. Instead, it should order activities by their date, since that order is relevant for the FIFO-method.

Please bear with me, this is my first ever PR for an open-source project. I am looking forward to your review! 🙏

### CODE REVIEW

**Review by codeofsumit — COMMENTED** [review]
Wow this is a positive surprise 👏  - is it christmas already?
These are great additions, congrats on your first PR 🚀 
How about adding a CI job so the tests run via Github Actions on every PR?
https://docs.github.com/en/actions/guides/building-and-testing-nodejs

**Comment by naduweisstschon** [comment]
Thanks, man - I appreciate it!

I have already added a GitHub workflow file that I've yoinked from the Tresor import project. Is there anything else that has to be done? Doesn't GitHub automagically create an action from that?

**Comment by codeofsumit** [comment]
Good point. @johakr can you help
out here? What's required to run the tests via GitHub Actions as we do in the API repo?

**Comment by johakr** [comment]
@codeofsumit Since it's a PR from a fork which introduces the Workflow, it currently only runs on the forked repo: https://github.com/naduweisstschon/tresor-returns/actions

As soon as the PR is merged, actions should run in this repo automagically as well 👍

**Pull request closed without merging**
